name: deploy react app
on: push
jobs:
  deploy-react-react:
    runs-on: ubuntu-latest
    steps: 
       - name: clone the repository
         run: actions/checkout@v4
       - name: install npm packages
         run: npm install
       - name: run npm
         run: npm run build 
       - name: start npm
         run: npm start
